name: blogs
recipe: symfony
config:
    php:              '8.2'
    via:              apache:2.4
    webroot:          public
    database:         mysql:8.0
    xdebug:           true
    composer_version: '2.6.2'

services:
    appserver:
        build_as_root:
            - apt-get update -y
            - apt-get install -y openssl
            - docker-php-ext-install sockets
            - docker-php-ext-enable sockets
        overrides:
            environment:
                PHP_IDE_CONFIG: "serverName=appserver"
                XDEBUG_SESSION_START: lando
                XDEBUG_CONFIG: "discover_client_host=0 client_host=host.docker.internal"

    phpmyadmin:
        type: phpmyadmin:5.1
        hosts:
            - database

proxy:
    phpmyadmin:
        - pma.lndo.site

keys: false